### ISSUE TITLE
Reply instead of raw tweeting

### ISSUE THREAD

**Issue by ghost** [tylerl0706/TechKnightsTwitterNodeDemo#2]
Hello,

I followed the steps from here : http://techknights.org/workshops/nodejs-twitterbot/ and found out the "reply.js" was not really a reply but a pure tweet and I can't find any way to change that. It's not really an isse or a bug, but I would like to know how to turn my reply to a real reply and not just a bare tweet, as it would be better IMHO for me as a dev and for the people using the bot. I can't find any way to do it neither here nor on https://www.npmjs.com/package/twitter and as I'm still new to coding I don't think I can figure it out by myself. 

Do you have any idea on how to do that? I would be really grateful if you did 😉

**Comment by TylerLeonhardt** [comment]
So you would like to programmatically reply to tweets, is that right? 

Example:
You: "Hi @mybot"
Bot: "@You: hi there"

**Comment by ghost** [comment]
Exactly ! I feel like it would be better for users because that way they would have the dialog with the bot in a thread and not with separate tweets.

**Comment by TylerLeonhardt** [comment]
*If I lose you anywhere, let me know*

So first off, it's important to note that the twitter npm package is basically just a wrapper for Twitter's API. If the npm package is complete enough, you should be able to interact with the API through the wrapper with little difficultly.

The Twitter API docs for the REST API are [here](https://dev.twitter.com/rest/reference)!

Skimming through, we can see something that might look familiar: `POST statuses/update`

So really - the twitter wrapper simply takes the data you give it and does a POST http request to the `statuses/update` endpoint.

[Here](https://dev.twitter.com/rest/reference/post/statuses/update) are the docs for that endpoint.

Looking at the parameters, you can see: `in_reply_to_status_id` which is an optional parameter that says:


_The ID of an existing status that the update is in reply to. Note: This parameter will be ignored unless the author of the Tweet this parameter references is mentioned within the status text. Therefore, you must include @username , where username is the author of the referenced Tweet, within the update._


So going back to the twitter npm package, that might look something like this:

```
var tweetObj = {
  status: '@NelsonTriesCoding: I love Tech Knights!',
  in_reply_to_status_id: 12341234
}
Twitter.post('statuses/update', tweetObj,  function(error, tweet, response){
  if(error){
    console.log(error);
  }
  console.log(tweet);  // Tweet body.
  console.log(response);  // Raw response object.
});
```

Since the tutorial shows you how to reply with a pure tweet, I think this is enough information to get you started and you can finish the rest. That way it's still a learning experience and not me telling you what to do! :) 

Let me know if you still need help!

**Comment by TylerLeonhardt** [comment]
I'm going to close this now. If you still need help, let me know.
